/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#ffb1c2",
        "outline": "#8d6f75",
        "on-secondary-fixed-variant": "#721199",
        "on-secondary-container": "#600084",
        "on-surface-variant": "#594045",
        "secondary-container": "#d97dff",
        "secondary-fixed": "#f8d8ff",
        "surface-container": "#ffe7f7",
        "on-tertiary": "#ffffff",
        "primary": "#F06292",
        "surface-container-highest": "#fad9f1",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#604100",
        "surface-bright": "#fff7f9",
        "surface-tint": "#b90c55",
        "outline-variant": "#e1bec4",
        "glass-overlay": "rgba(255, 255, 255, 0.15)",
        "tertiary": "#684600",
        "surface-container-high": "#ffdff6",
        "on-primary-container": "#ffd9df",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#281900",
        "success-emerald": "#2E7D32",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#3f0018",
        "surface-container-low": "#ffeff8",
        "inverse-surface": "#3f293b",
        "error": "#ba1a1a",
        "background": "#fff7f9",
        "on-secondary-fixed": "#320047",
        "secondary": "#8c33b3",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#ffba38",
        "surface-variant": "#fad9f1",
        "bg-gradient-start": "#FFF3F6",
        "tertiary-container": "#875d00",
        "on-tertiary-container": "#ffdead",
        "secondary-fixed-dim": "#ebb2ff",
        "tertiary-fixed": "#ffdeac",
        "primary-container": "#F06292",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#8f003f",
        "inverse-primary": "#ffb1c2",
        "primary-fixed": "#ffd9df",
        "on-surface": "#281526",
        "on-background": "#281526",
        "glass-border": "rgba(255, 255, 255, 0.4)",
        "inverse-on-surface": "#ffebf7",
        "bg-gradient-end": "#F3E5F5",
        "surface": "#fff7f9",
        "surface-dim": "#f1d1e8"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-max": "1440px",
        "stack-md": "16px",
        "stack-sm": "8px",
        "stack-xl": "64px",
        "stack-lg": "32px",
        "margin-desktop": "80px",
        "gutter": "24px",
        "margin-mobile": "20px"
      },
      fontFamily: {
        "body-lg": ["Fira Sans"],
        "headline-lg-mobile": ["Epilogue"],
        "headline-lg": ["Epilogue"],
        "headline-md": ["Epilogue"],
        "label-sm": ["Archivo Narrow"],
        "body-md": ["Fira Sans"]
      },
      fontSize: {
        "body-lg": ["21px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-lg-mobile": ["34px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "headline-lg": ["44px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "headline-md": ["28px", { "lineHeight": "1.3", "fontWeight": "500" }],
        "label-sm": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "body-md": ["18px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "xs": ["14px", { "lineHeight": "1.1rem" }],
        "sm": ["16px", { "lineHeight": "1.35rem" }],
        "base": ["18px", { "lineHeight": "1.6rem" }],
        "lg": ["21px", { "lineHeight": "1.85rem" }],
        "xl": ["23px", { "lineHeight": "1.85rem" }],
        "2xl": ["27px", { "lineHeight": "2.1rem" }]
      }
    }
  },
  plugins: [],
};
